Projects/Kudos-Slackbot.md
README.md

Add Kudos idea and update app description in README.md
Resolves: N/a
See also: N/a

Refactor: Add Kudos idea and update app description in README.md

---

Projects/Slack-Archiver.md
README.md

Add Slack Archiver application idea
- Note that this is an advanced application. Although the requirements are small
there are a number of complex implementation details.
- This application will also require considerable design.
Resolves: N/a
See also: N/a

Feature: Add Slack Archiver application idea

---

Projects/Christmas-Lights-App.md
README.md

Add Ripple Lights application specification
Resolves: N/a
See also: N/a

Feature: Add Ripple Lights application specification

---

README.md

Add Windchill link to application table in README.md
Resolves: N/a
See also: N/a

Refactor: Add Windchill link to application table in README.md

---

Projects/Flip-Image-App.md
README.md

Add Flip Image App specification
Resolves: N/a
See also: N/a

Feature: Add Flip Image App specification

---

Projects/True-or-False-App.md
README.md

Add TrueOrFalse app specification
Resolves: N/a
See also: N/a

Feature: Add TrueOrFalse app specification

---

Projects/Bin2Dec-App.md
README.md

Add Bin2Dec application specification
Resolves: N/a
See also: N/a

Feature: Add Bin2Dec application specification

---

Projects/Color-Cycle-App.md
README.md

Add Color Cycle application specification
Resolves: N/a
See also: N/a

Feature: Add Color Cycle application specification

---

Projects/FlashCards-App.md
README.md

Add Flashcards app specification
Resolves: N/a
See also: N/a

Feature: Add Flashcards app specification

---

Projects/SpellIt-App.md
README.md

Add spell-It app specification
Resolves: N/a
See also: N/a

Feature: Add Spell-It app specification

---

Projects/GitHub-Timeline-App.md
README.md

Add GitHub Timeline app specification
Resolves: N/a
See also: N/a

Feature: Add GitHub Timeline app specification

---

Projects/Bin2Dec-App.md
Projects/Book-Finder-App.md
Projects/Cause-Effect-App.md
Projects/Christmas-Lights-App.md
Projects/Color-Cycle-App.md
Projects/FlashCards-App.md
Projects/Flip-Image-App.md
Projects/GitHub-Timeline-App.md
Projects/Kudos-Slackbot.md
Projects/Lorem-Ipsum-Generator.md
Projects/Markdown-Previewer.md
Projects/Markdown-Table-Generator.md
Projects/Notes-App.md
Projects/Pomodoro-Clock.md
Projects/Slack-Archiver.md
Projects/Slider-Design.md
Projects/SpellIt-App.md
Projects/String-Art.md
Projects/Timezone-Slackbot.md
Projects/To-Do-App.md
Projects/True-or-False-App.md
Projects/Windchill-App.md
README.md

Add application summary information
- Add app description and tier at the top of each application specification
- Change the app table in README.md to contain description and tier
- Add definition of the experience required for each tier
Resolves: #17
See also: N/a

Refactor: Add application summary information

---

Projects/Cause-Effect-App.md
Projects/FlashCards-App.md
Projects/GitHub-Timeline-App.md
Projects/SpellIt-App.md
README.md

Add missing Trello boards to app specifications
Resolves: N/a
See also: N/a

Refactor: Add missing Trello boards to app specifications

---

Projects/SportsBracket-App.md
README.md

Add Sport Bracket Generator app specification
Resolves: N/a
See also: N/a

Feature: Add Sports Bracket Generator app specification

---

Example Guide.md
Projects/Survey-App.md
README.md

- Add Survey app specification
- Update the specification template to include a 'Project Board' section
defining the link to the projects Kanban board, currently Trello.
Resolves: N/a
See also: N/a

Feature: Add Survey app specification

---

Projects/Roman2Dec-App.md

Hi @florinpop17,
Please see this app request, not sure if would fit the standards, but just came into my mind. Most of the content I copied from the wikipedia but I checked that is correct.
The idea is that the user is able to create a Roman to Decimal converter.
Regards,
Victor

[feature] Created the proposal for a Roman2Dec-App idea.

---

README.md

Update project documentation to match FCC article
Resolves: N/a
See also: N/a

Refactor: Update project documentation to match FCC article

---

Projects/Book-Finder-App.md
Projects/RegExp-Helper-App.md
Projects/String-Art.md
README.md

Add RegExp Helper app specification
Resolves: N/a
See also: N/a

Feature: Add RegExp Helper app specification

---

Projects/JSON2CSV-App.md
README.md

Add JSON2CSV app specification
Resolves: N/a
See also: N/a

Feature: Add JSON2CSV app specification

---

Projects/CSV2JSON-App.md
README.md

Add CSV2JSON app specification
Resolves: N/a
See also: N/a

Feature: Add CSV2JSON app specification

---

Projects/Elevator-App.md
README.md

Add Elevator app specification
Resolves: N/a
See also: N/a

Feature: Add Elevator app specification

---

Projects/FastFood-App.md
README.md

Add FastFood simulator app specification.
Resolves: N/a
See also: N/a

Feature: Add FastFood simulator app specification

---

Projects/Shell-Game.md
README.md

Add Shell game app specification
Resolves: N/a
See also: N/a

Feature: Add Shell game app specification

---

Projects/Typing-Practice-App.md
README.md

Add Typing Practice app specification
Resolves: N/a
See also: N/a

Feature: Add Typing Practice app specification

---

Projects/Recipe-App.md
README.md

Add Recipe app specification
Resolves: N/a
See also: N/a

Feature: Add Recipe app specification

---

Projects/Product-Landing-Page.md
Projects/Simple-Online-Store.md
README.md

Add Simple Online Store app specification
Resolves: N/a
See also: N/a

Feature: Add Simple Online Store app specification

---

Projects/Calorie-Counter-App.md
README.md

Add Calorie Counter app specification
Resolves: N/a
See also: N/a

Feature: Add Calorie Counter app specification

---

Projects/Instagram-Clone-App.md
README.md

Hey Florin,
I recently started doing an Instagram clone on my YouTube channel and thought that it is a great learning experience.
I thought that it would be great for your app ideas repo.
Let me know your thoughts :)

Added Instagram Clone to Advanced app ideas

---

Projects/GitHub-Status-App.md
README.md

Add GitHub Status app specification
Resolves: N/a
See also: N/a

Feature: Add GitHub Status app specification

---

Projects/Podcast-Directory-App.md
README.md

Add Podcast Directory app specification
Resolves: N/a
See also: N/a

Feature: Add Podcast Directory app specification

---

Projects/Notes-App.md

I've built similar app with Theme support using React. I would like to add it in your examples section.

Added example project built with react

---

Projects/MyPodcast-Library-app.md
Projects/Podcast-Directory-App.md
README.md

Add MyPodcast Library app specification
Resolves: N/a
See also: N/a

Feature: Add MyPodcast Library app specification

---

Projects/Word-Frequency-App.md
README.md

Add Word Frequency app specification
Resolves: N/a
See also: N/a

Feature: Add Word Frequency app specification

---

Projects/Dynamic-CSSVar-app.md
README.md

Add Dynamic CSS Variables app specification
Resolves: N/a
See also: N/a

Feature: Add Dynamic CSS Variables app specification

---

Projects/Shuffle-Deck-App.md
README.md

Add Shuffle Deck app specification
Resolves: N/a
See also: N/a

Feature: Add Shuffle Deck app specification

---

Projects/Bit-Masks-App.md
README.md

Add Bit Mask app specification
Resolves: N/a
See also: N/a

Feature: Add Bit Mask app specification

---

Projects/Bug-Race-Game.md
README.md

Add Bug Race game specification
Resolves: N/a
See also: N/a

Feature: Add Bug Race game specification

---

Projects/GitTweet-App.md
README.md

Add GitTweet app specification
Resolves: N/a
See also: N/a

Feature: Add GitTweet app specification

---

Projects/Pearson-Regression-App.md
README.md

Add Pearson Regression app specification
Resolves: N/a
See also: N/a

Feature Add Pearson Regression app specification

---

Projects/Kudos-Slackbot.md

Added a sample project to Kudos-Slackbot.md.
https://cubic-quince.glitch.me/

Add Sample Project to Kudos-Slackbot.md

---

Projects/Movie-App.md
README.md

- Project file added with all info as requested
- Project title added on tier 3 Advance on main Readme
Hope this looks good, Thanks!

Project: Movie Database App Add

---

Projects/Hello-App.md
README.md

Add Hello app specification
Resolves: N/a
See also: N/a

Feature: Add Hello app specification

---

Projects/QRCode-Badge-App.md
README.md

Add QRCode Badge Generator app specification
Resolves: N/a
See also: N/a

Feature: Add QRCode Badge Generator app specification

---

Projects/IOT-Mailbox-App.md
README.md

Add IoT Mailbox simulator app specification
Resolves: N/a
See also: N/a

Feature: Add IoT Mailbox simulator app specification

---

Projects/NASA-Exoplanet-Query.md
README.md

Add NASA Exoplanet Query app specification
Resolves: N/a
See also: N/a

Feature: Add NASA Exoplanet Query app specification

---

Projects/Sales-DB-App.md
README.md

Add Sales Receipt app specification
Resolves: N/a
See also: N/a

Feature: Add Sales Receipt app specification

---

Projects/Boole-Bot-Game.md

Add requirement to assign boolean value to bot's
Resolves: N/a
See also: N/a

Fix: Add requirement to assign boolean value to bot's

---

Projects/Flip-Art-App.md
README.md

Add Flip Art app specification
Resolves: N/a
See also: N/a

Feature: Add Flip Art app specification

---

Projects/Vigenere-Cipher.md
README.md

Add Vigenere Cipher app specification
Resolves: N/a
See also: N/a

Feature: Add Vigenere Cipher app specification

---

Projects/Quiz-App.md

Added My React Quiz App as a Example Project

Added React Quiz PWA

---

Projects/Pomodoro-Clock.md

Hi there,
[Pomolectron](https://github.com/amitmerchant1990/pomolectron) is a pomodoro desktop app for menubar/tray. It's built on top of [Electron](https://electronjs.org). I think it would be a nice example to implement for a beginners.
Regards.

Add Pomolectron

---

Example Guide.md

Did a little editing i nthe Example Guide.md

tighten up the language

---

Projects/1-Beginner/Word-Frequency-App.md
Projects/2-Intermediate/Podcast-Directory-App.md
Projects/2-Intermediate/Sales-DB-App.md
Projects/3-Advanced/MyPodcast-Library-app.md
Projects/3-Advanced/NASA-Exoplanet-Query.md

There were several internal broken links, I fixed all of them

Fixed all broken internal links

---

Projects/2-Intermediate/math-editor.md
README.md

Hi!
Thought it would be a cool idea to add an app that would be useful to students like me. The isn't that hard to implement but still requires some knowledge of web or desktop programming so I put on intermediate.

Added a new app idea: math editor for students

---

Projects/1-Beginner/Stopwatch-App.md

I developed the stopwatch application with the svelte framework. 
Let me know if it is more appropriate to link the project through the REPL (I added a link in the codepen's description).

add a stopwatch app developed with svelte

---

Projects/2-Intermediate/GitHub-Profiles.md
README.md

- Add GitHub-Profiles.md in 2-Intermediate
- Add GitHub Profiles in Readme.md

Add GitHub Profiles

---

Projects/1-Beginner/Stopwatch-App.md
Projects/1-Beginner/Word-Frequency-App.md

Good evening Florin. 
Out of inexperience using git with a forked repository I accidentally made more commits than I would have liked. However, I am positive that the only addition I made to the repo is the link to the project on CodePen.
Sorry for the inconvenience. I'll be sure to review my notes on git.

Add word-frequency-app developed with svelte

---

Projects/2-Intermediate/Name-Generator.md
README.md

Intermediate App idea using Neural Networks

Added Name-Generator idea

---

Projects/2-Intermediate/Charity-Finder-App.md

Fix typo in charity-finder-app.md

---

Projects/2-Intermediate/Image-Scaner.md
README.md

Image scanner for emails, phone numbers and website links as the new intermediate app idea added

Added new Intermediate app idea Image Scanner

---

Projects/3-Advanced/Survey-App.md

I built a React app using the specifications from the Survey App Tier 3 project. It would be nice if i could add it as an example project 😃

Add survey app example

---

Projects/3-Advanced/Chat-App.md

The chat application was written in C# using TCP sockets

Added example project

---

Projects/1-Beginner/CSV2JSON-App.md
Projects/1-Beginner/JSON2CSV-App.md

Hey there! I'm Gabriel. 
I met this amazing repo on youtube. And my first completed project for this repo is the JSON/CSV converter. Hope you enjoy my example project and may put this in the original guide!

Added my completed project example

---

Projects/1-Beginner/Calculator-App.md

So, this calculator app that I have created is bundled with a lot of functionalities and is completely robust. It has functionalities like "plus-minus", "dot" etc.

Added an Example Project

---

Projects/2-Intermediate/GitHub-Profiles.md

Removed old not found example (https://chaharshivam.github.io/github-profiles/?#) and added a new one (https://github-profiles.netlify.app/).

Updated Github Profiles

---

Projects/1-Beginner/Calculator-App.md
Projects/2-Intermediate/Card-Memory-Game.md

Adding my own Neumorphic Calculator Example

---

Projects/1-Beginner/Calculator-App.md

I added a new python example for Beginner calculator-app.  Let me know if it works

Added a new example to Calculator-App.md

---

Projects/2-Intermediate/Book-Finder-App.md

I added this new link so that new people can take as an example of how to make a book finder.

Add new project example of book finder app

---

Projects/2-Intermediate/GitHub-Profiles.md

@florinpop17 The links to my project were borken, I forgot to update them. I'm submitting this change to fix it.

Updating broken links

---

Projects/3-Advanced/Movie-App.md

add two spaces at the end of the line to force newline

fixed newline issue

---

Projects/1-Beginner/Christmas-Lights-App.md

the new project example completes the user stories.

Add new project example of Christmas Light.

---

Projects/2-Intermediate/Currency-Converter.md
README.md

The idea has been added to readme and added to the appropriate project folder.

adding currency converter app idea
